version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "formula1-drivers-service"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "formula1-drivers-service"
parameter_overrides = "CorsAllowOrigin=\"http://formula1project.com\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
