-- Service-owned tables; apply as administrator. Never alters public.drivers.
BEGIN;
CREATE SCHEMA IF NOT EXISTS driver_stats;
REVOKE CREATE ON SCHEMA driver_stats FROM PUBLIC;
CREATE TABLE IF NOT EXISTS driver_stats.results (
    driver_id TEXT NOT NULL,
    season INTEGER NOT NULL CHECK (season >= 1950),
    round INTEGER NOT NULL CHECK (round > 0),
    session_type TEXT NOT NULL CHECK (session_type IN ('grand_prix', 'sprint')),
    position INTEGER NOT NULL CHECK (position > 0),
    position_text TEXT NOT NULL,
    grid INTEGER CHECK (grid >= 0),
    points NUMERIC NOT NULL,
    laps INTEGER CHECK (laps >= 0),
    source_status TEXT,
    outcome TEXT NOT NULL CHECK (outcome IN ('finished', 'dnf', 'non_start', 'disqualified', 'unknown')),
    source_payload JSONB NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (driver_id, season, round, session_type)
);
CREATE TABLE IF NOT EXISTS driver_stats.standings (
    driver_id TEXT NOT NULL,
    season INTEGER NOT NULL CHECK (season >= 1950),
    position INTEGER,
    points NUMERIC NOT NULL,
    source_round INTEGER NOT NULL,
    completed BOOLEAN NOT NULL,
    current_roster BOOLEAN NOT NULL DEFAULT FALSE,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (driver_id, season)
);
CREATE TABLE IF NOT EXISTS driver_stats.season_stats (
    driver_id TEXT NOT NULL,
    season INTEGER NOT NULL,
    championship_position INTEGER,
    total_points NUMERIC NOT NULL,
    total_wins INTEGER NOT NULL,
    total_dnfs INTEGER,
    grand_prix_entries INTEGER,
    grand_prix_finishes INTEGER,
    grand_prix_wins INTEGER,
    grand_prix_podiums INTEGER,
    grand_prix_pole_starts INTEGER,
    grand_prix_top_10_finishes INTEGER,
    grand_prix_dnfs INTEGER,
    grand_prix_points NUMERIC,
    grand_prix_best_finish INTEGER,
    grand_prix_best_finish_count INTEGER,
    grand_prix_best_grid INTEGER,
    grand_prix_best_grid_count INTEGER,
    sprint_entries INTEGER,
    sprint_finishes INTEGER,
    sprint_wins INTEGER,
    sprint_podiums INTEGER,
    sprint_pole_starts INTEGER,
    sprint_top_10_finishes INTEGER,
    sprint_dnfs INTEGER,
    sprint_points NUMERIC,
    sprint_best_finish INTEGER,
    sprint_best_finish_count INTEGER,
    sprint_best_grid INTEGER,
    sprint_best_grid_count INTEGER,
    completeness JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (driver_id, season)
);
CREATE TABLE IF NOT EXISTS driver_stats.career_stats (
    driver_id TEXT NOT NULL,
    through_season INTEGER NOT NULL,
    world_championships INTEGER,
    total_points NUMERIC NOT NULL,
    total_wins INTEGER NOT NULL,
    total_dnfs INTEGER,
    grand_prix_entries INTEGER,
    grand_prix_finishes INTEGER,
    grand_prix_wins INTEGER,
    grand_prix_podiums INTEGER,
    grand_prix_pole_starts INTEGER,
    grand_prix_top_10_finishes INTEGER,
    grand_prix_dnfs INTEGER,
    grand_prix_points NUMERIC,
    grand_prix_best_finish INTEGER,
    grand_prix_best_finish_count INTEGER,
    grand_prix_best_grid INTEGER,
    grand_prix_best_grid_count INTEGER,
    sprint_entries INTEGER,
    sprint_finishes INTEGER,
    sprint_wins INTEGER,
    sprint_podiums INTEGER,
    sprint_pole_starts INTEGER,
    sprint_top_10_finishes INTEGER,
    sprint_dnfs INTEGER,
    sprint_points NUMERIC,
    sprint_best_finish INTEGER,
    sprint_best_finish_count INTEGER,
    sprint_best_grid INTEGER,
    sprint_best_grid_count INTEGER,
    completeness JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (driver_id)
);
CREATE TABLE IF NOT EXISTS driver_stats.sync_runs (
    run_id UUID PRIMARY KEY,
    season INTEGER NOT NULL,
    mode TEXT NOT NULL,
    source_round INTEGER NOT NULL,
    roster_ids JSONB NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    outcome TEXT NOT NULL CHECK (outcome IN ('running', 'success', 'failed')),
    completed_drivers JSONB NOT NULL DEFAULT '[]',
    driver_count INTEGER NOT NULL DEFAULT 0,
    error_type TEXT
);
CREATE INDEX IF NOT EXISTS stats_sync_runs_started ON driver_stats.sync_runs (started_at DESC);
COMMIT;
